package com.github.bkmbigo.basicapplication.domain

import com.github.bkmbigo.basicapplication.domain.models.Note
import kotlinx.coroutines.flow.Flow

interface NoteRepository {

    /**
     * Returns a flow of list of notes obtained from the database
     */
    suspend fun getAllNotes(): Flow<List<Note>>

    /**
     * Returns a single note from the database as specified by the [id].
     * Returns a null object when the note is not found in the database.
     */
    suspend fun getNote(id: Long): Note?

    /** Adds the [note] to the database. Returns the new Primary key generated by the database
     */
    suspend fun insertNote(note: Note): Long

    /**
     * Updates the [note] entity in the database
     */
    suspend fun updateNote(note: Note)

    /**
     * Deletes the [note] from the database
     */
    suspend fun deleteNote(note: Note)
}